### ISSUE TITLE
python setup.py --user does not result in a working installation

### ISSUE THREAD

**Issue by antoneliasson** [muflone/gwakeonlan#10]
$ cd ~/git
    $ git clone https://github.com/muflone/gwakeonlan
    $ cd gwakeonlan
    $ python setup.py install --user
    [...]
    $ gwakeonlan
	/home/anton/.local/lib/python2.7/site-packages/gwakeonlan/functions.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
	  from gi.repository import Gtk

This works fine. However, launching gwakeonlan from a different directory fails:

    $ cd ~
    $ gwakeonlan
	/home/anton/.local/lib/python2.7/site-packages/gwakeonlan/functions.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
	  from gi.repository import Gtk
	Traceback (most recent call last):
	  File "/home/anton/.local/lib/python2.7/site-packages/gwakeonlan/app.py", line 38, in startup
		self.ui = MainWindow(self, self.settings)
	  File "/home/anton/.local/lib/python2.7/site-packages/gwakeonlan/ui.py", line 41, in __init__
		self.loadUI()
	  File "/home/anton/.local/lib/python2.7/site-packages/gwakeonlan/ui.py", line 69, in loadUI
		builder.add_from_file(FILE_UI_MAIN)
	GLib.Error: g-file-error-quark: Failed to open file '/usr/share/gwakeonlan/ui/main.glade': No such file or directory (4)
	Traceback (most recent call last):
	  File "/home/anton/.local/lib/python2.7/site-packages/gwakeonlan/app.py", line 55, in activate
		self.ui.run()
	AttributeError: 'Application' object has no attribute 'ui'

**Comment by Lukasz-Pe** [comment]
Same here. Only installed without parameter `--user`.

**Comment by debian-alain** [comment]
no solution for me 
works in its directory only . not in user

**Comment by muflone** [comment]
fixed in gWakeOnLAN 0.8
