### ISSUE TITLE
Status of version 0.6.3

### ISSUE THREAD

**Issue by ryandesign** [muflone/gwakeonlan#12]
The Releases tab of this GitHub repository shows that 0.6.2 is the latest release. A tag for 0.6.3 exists, but a GitHub Release for it does not, there are no release notes, there are no attached files. Is there something wrong with the 0.6.3 release—some reason why we should not use it? If not, can a GitHub Release be created for it and can it be marked as the latest release?

**Comment by muflone** [comment]
There's nothing wrong with the 0.6.3 version.
As it was only a translations update I forgot to make a release for it.

In the next hours I'll attach the extra download files.

**Comment by muflone** [comment]
Fixed
