### ISSUE TITLE
gwakeonlan should be ported to Python 3 because of Python 2 deprecation

### ISSUE THREAD

**Issue by N0rbert** [muflone/gwakeonlan#17]
The great and useful `gwakeonlan` package was removed from latest versions of [Debian](https://packages.debian.org/search?suite=all&searchon=names&keywords=gwakeonlan) and [Ubuntu](https://packages.ubuntu.com/search?suite=all&exact=1&searchon=names&keywords=gwakeonlan) because of Python 2 deprecation, please port it to Python 3.

**Comment by mfdewit** [comment]
Or maybe a Snap/Flatpak package could be created? This way, there is no dependency on the system version of Python.

**Comment by muflone** [comment]
Fixed in version 0.7.0
