### ISSUE TITLE
Distutils script install in /usr/local/share but executable wants /usr/share

### ISSUE THREAD

**Issue by theblackhole** [muflone/gwakeonlan#18]
Hello,

When I do a `sudo python3 setup.py install`, it installs gwakeonlan files in /usr/local/share but when I execute gwakeonlan, it crashes because it tries to load files (main.glide, etc...) from /usr/share.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gwakeonlan/app.py", line 38, in startup
    self.ui = MainWindow(self, self.settings)
  File "/usr/local/lib/python3.8/dist-packages/gwakeonlan/ui.py", line 45, in __init__
    self.loadUI()
  File "/usr/local/lib/python3.8/dist-packages/gwakeonlan/ui.py", line 73, in loadUI
    builder.add_from_file(FILE_UI_MAIN)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/share/gwakeonlan/ui/main.glade”: Aucun fichier ou dossier de ce type (4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gwakeonlan/app.py", line 55, in activate
    self.ui.run()
AttributeError: 'Application' object has no attribute 'ui'
```

`whereis gwakeonlan` returns `gwakeonlan: /usr/local/bin/gwakeonlan`

My workaround atm is to create symlinks to make it work :
```sh
sudo ln -s /usr/local/share/doc/gwakeonlan/ /usr/share/doc/gwakeonlan
sudo ln -s /usr/local/share/gwakeonlan/ /usr/share/gwakeonlan
```

----
os : Ubuntu 20.04 LTS
gwakeonlan version : master (commit bca20ea)
python version : 3.8.2

Btw thanks for making this app, I use it everyday :)

**Comment by edwkmho** [comment]
Thanks for the great app and recent update.

I am also experiencing the same problem in Ubuntu 20.04.

**Comment by rmkimathi** [comment]
Bug confirmed here too. Workaround proposed fixes the issue. Thanks

**Comment by muflone** [comment]
That part was rewritten and setup.py now supports --user flag (see #10 )
