### ISSUE TITLE
Pip/snap/flatpak

### ISSUE THREAD

**Issue by theblackhole** [muflone/gwakeonlan#19]
Hello,

It's all in the title :)
A pip, snap and flatpak package would be nice to have, even if it's still a 0.x release.

A pip package could be the first step since you're already using distutils

**Comment by wechsler42** [comment]
Hi there,
I would second this. Since there are no more .deb packages which work on Ubuntu 20.04 LTS I am left without Gwakeonlan. Building a snap or flatpak would be helpful.

**Comment by zocker-160** [comment]
I have created an PR for Appimage, I think this makes the most sense for a project like this.

Here is the file if you want to test it.
[gwakeonlan-Appimage-0.7.0-x86_64.zip](https://github.com/muflone/gwakeonlan/files/6105161/gwakeonlan-0.7.0-x86_64.zip)

**Comment by edwkmho** [comment]
Thanks for the creating the appimage, unfortunately when i run it with Fedora 34 it won't work.

Would it be possible for you to create a rpm package in this case. 

Thank you in advance.

**Comment by zocker-160** [comment]
@edwkmho could you please share some more information, like the output when launching it from terminal?
I sadly cannot test all bazillion distros that are out there.

> Would it be possible for you to create a rpm package or flatpak in this case.

RPM is a clear no from my side, but Flatpak should work, I will look into that.

**Comment by edwkmho** [comment]
@zocker-160

Many thanks for your prompt response. 

I managed to achieve what i wanted with Remmina app using the exec
plug-in. 

I am terribly sorry to trouble. 

Thanks once again for the assistant.
 
-- 
KM HO
+60193989918

-----Original Message-----
From: zocker-160 ***@***.***>
Reply-To: muflone/gwakeonlan
***@***.***>
To: muflone/gwakeonlan ***@***.***>
Cc: edwkmho ***@***.***>, Mention
***@***.***>
Subject: Re: [muflone/gwakeonlan] Pip/snap/flatpak (#19)
Date: Sat, 05 Jun 2021 02:30:54 -0700

@edwkmho could you please share some more information, like the output
when launching it from terminal?
I sadly cannot test all bazillion distros that are out there.
> Would it be possible for you to create a rpm package or flatpak in
> this case.
RPM is a clear no from my side, but Flatpak should work, I will look
into that.

**Comment by muflone** [comment]
I've added an AppImage download for both 0.7 and 0.8 versions, based on the PR #21 
Please test it as it's my first AppImage
