### ISSUE TITLE
double click to wake a machine

### ISSUE THREAD

**Issue by playgithub** [muflone/gwakeonlan#23]
Now I should check item(s) and click button `Turn on`.
If a machine can be wake up by double clicking an item, it'll more convienient.
Thanks

**Comment by muflone** [comment]
gWakeOnLAN 0.8 allows you to turn on a machine by simply highlighting it and click turn on without any selection checkbox. As an alternative you could just press CTRL+Enter

I won't implement the double click as it's currently used to edit a machine detail
