### ISSUE TITLE
Support for Debian 11?

### ISSUE THREAD

**Issue by saudiqbal** [muflone/gwakeonlan#24]
Is it possible to add support for Debian 11 or a compiled deb file.

**Comment by hosiet** [comment]
Currently gwakeonlan is available in Debian 11 via `bullseye-backports` repository. To use the package in Debian official repo, please enable `bullseye-backports` repository as indicated in https://backports.debian.org/ , and then install the software using `sudo apt install gwakeonlan`.

Reference: https://tracker.debian.org/pkg/gwakeonlan

**Comment by muflone** [comment]
Packages for Debian and Ubuntu distributions were just released for gWakeOnLAN 0.8.0
