### ISSUE TITLE
support for debian 12 / sid  ?

### ISSUE THREAD

**Issue by debian-alain** [muflone/gwakeonlan#25]
Téléchargement : 

 $ cd Téléchargements/gwakeonlan
~/Téléchargements/gwakeonlan$ ls
build          gwakeonlan     locale     requirements_development.txt  ui
create-pot.sh  gwakeonlan.py  man        requirements_travis.txt
data           icons          po         requirements.txt
doc            LEGGIMI.md     README.md  setup.py

installation : 

~/Téléchargements/gwakeonlan$ sudo python3 setup.py install 
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
copying build/scripts-3.9/gwakeonlan.py -> /usr/local/bin
changing mode of /usr/local/bin/gwakeonlan.py to 755
renaming the python script /usr/local/bin/gwakeonlan.py -> /usr/local/bin/gwakeonlan
running install_data
Installing icons...
copying /home/alain/Téléchargements/gwakeonlan/locale/en/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/en/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/tr/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/tr/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/de/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/de/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/zh_TW/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/zh_TW/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/he/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/he/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/ca/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/ca/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/eu/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/eu/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/ru/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/ru/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/sl_SI/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/sl_SI/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/es/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/es/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/it/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/it/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/bg/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/bg/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/sk/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/sk/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/fr/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/fr/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/ko_KR/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/ko_KR/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/pt_BR/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/pt_BR/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/lt/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/lt/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/pl/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/pl/LC_MESSAGES
copying /home/alain/Téléchargements/gwakeonlan/locale/nl/LC_MESSAGES/gwakeonlan.mo -> /usr/local/share/locale/nl/LC_MESSAGES
running install_egg_info
Removing /usr/local/lib/python3.9/dist-packages/gWakeOnLAN-0.7.0.egg-info
Writing /usr/local/lib/python3.9/dist-packages/gWakeOnLAN-0.7.0.egg-info
~/Téléchargements/gwakeonlan$ 

retour dans le /home 
~/Téléchargements/gwakeonlan$ cd 

lancement de la commande : 

$ gwakeonlan
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/app.py", line 38, in startup
    self.ui = MainWindow(self, self.settings)
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/ui.py", line 45, in __init__
    self.loadUI()
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/ui.py", line 73, in loadUI
    builder.add_from_file(FILE_UI_MAIN)
gi.repository.GLib.Error: g-file-error-quark: L’ouverture du fichier « /usr/share/gwakeonlan/ui/main.glade » a échoué : Aucun fichier ou dossier de ce type (4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/app.py", line 55, in activate
    self.ui.run()
AttributeError: 'Application' object has no attribute 'ui'

$ sudo gwakeonlan
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/app.py", line 38, in startup
    self.ui = MainWindow(self, self.settings)
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/ui.py", line 45, in __init__
    self.loadUI()
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/ui.py", line 73, in loadUI
    builder.add_from_file(FILE_UI_MAIN)
gi.repository.GLib.Error: g-file-error-quark: L’ouverture du fichier « /usr/share/gwakeonlan/ui/main.glade » a échoué : Aucun fichier ou dossier de ce type (4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gwakeonlan/app.py", line 55, in activate
    self.ui.run()
AttributeError: 'Application' object has no attribute 'ui'

$ python3 ~/Téléchargements/gwakeonlan/gwakeonlan.py
Traceback (most recent call last):
  File "/home/alain/Téléchargements/gwakeonlan/gwakeonlan/app.py", line 38, in startup
    self.ui = MainWindow(self, self.settings)
  File "/home/alain/Téléchargements/gwakeonlan/gwakeonlan/ui.py", line 45, in __init__
    self.loadUI()
  File "/home/alain/Téléchargements/gwakeonlan/gwakeonlan/ui.py", line 73, in loadUI
    builder.add_from_file(FILE_UI_MAIN)
gi.repository.GLib.Error: g-file-error-quark: L’ouverture du fichier « /usr/share/gwakeonlan/ui/main.glade » a échoué : Aucun fichier ou dossier de ce type (4)
Traceback (most recent call last):
  File "/home/alain/Téléchargements/gwakeonlan/gwakeonlan/app.py", line 55, in activate
    self.ui.run()
AttributeError: 'Application' object has no attribute 'ui'

comprends rien 

d'où vient l'erreur ?

$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	unstable
Codename:	sid
$ uname -a 
Linux sid 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

**Comment by hosiet** [comment]
Currently gwakeonlan is available in Debian Testing (Debian 12). Please install it via `sudo apt install gwakeonlan`.

Reference: https://tracker.debian.org/pkg/gwakeonlan

**Comment by muflone** [comment]
Packages for Debian and Ubuntu distributions were just released for gWakeOnLAN 0.8.0
