### ISSUE TITLE
Make it possible to delete all selected machines.

### ISSUE THREAD

**Issue by ypid** [muflone/gwakeonlan#5]
Currently even when multiple machines are selected (COL_SELECTED) only the last one is deleted. One would expect at least a question if the last one or all selected machines should be deleted.

**Comment by muflone** [comment]
There are two way to select hosts.
1. using the checkbox
2. using the highlighted line

The deletion feature uses the 2.

If you have the following situation

![immagine](https://user-images.githubusercontent.com/1284163/81021891-8f4cab00-8e6c-11ea-8c9e-6fe231f0a414.png)

when you click the deletion button, only the second host will be removed, regardless the checked state of other lines

**Comment by ypid** [comment]
Thanks for the details. Better late than never :)
